[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]
optimizer = true
optimizer_runs = 200
evm_version = "paris"

# Opcional: para pruebas con RPC fork
# Se puede comentar si se va a usar
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC}"
